import type { TrendRule } from './types'

export const TREND_RULES: TrendRule[] = [
  {
    id: 'TREND_P_1',
    name: 'Persistent high pain',
    domain: 'pain',
    flagLevel: 3,
    clinicianFlagLabel: 'High pain (score ≥ 3) reported in 3+ check-ins within 7 days',
    safetyAction: 'show_resources',
    patientMessage: 'You have had high pain several days in a row. Please talk to your care team about pain management.',
    notifyClinician: true,
    windowDays: 7,
    minOccurrences: 3,
  },
  {
    id: 'TREND_MH_1',
    name: 'Persistent low mood or hopelessness',
    domain: 'mental_health',
    flagLevel: 3,
    clinicianFlagLabel: 'Severe low mood or hopelessness (score ≥ 3) in 3+ check-ins within 7 days',
    safetyAction: 'show_resources',
    patientMessage: 'You have felt very low several days in a row. Please tell your care team how you have been feeling.',
    notifyClinician: true,
    windowDays: 7,
    minOccurrences: 3,
  },
  {
    id: 'TREND_MH_2',
    name: 'Recurring suicidal ideation',
    domain: 'mental_health',
    flagLevel: 4,
    clinicianFlagLabel: 'Self-harm thoughts endorsed in 2+ check-ins within 14 days — URGENT',
    safetyAction: 'urgent_care',
    patientMessage: 'You have shared difficult thoughts more than once recently. Please reach out to your care team or a crisis line today.',
    notifyClinician: true,
    windowDays: 14,
    minOccurrences: 2,
  },
  {
    id: 'TREND_MED_1',
    name: 'Persistent medication non-adherence',
    domain: 'medication',
    flagLevel: 3,
    clinicianFlagLabel: 'Medication missed or changed (score ≥ 2) in 4+ check-ins within 14 days',
    safetyAction: 'show_resources',
    patientMessage: 'You have been having trouble with your medication. Your care team can help.',
    notifyClinician: true,
    windowDays: 14,
    minOccurrences: 4,
  },
  {
    id: 'TREND_DIET_1',
    name: 'Repeated insufficient eating',
    domain: 'diet',
    flagLevel: 3,
    clinicianFlagLabel: 'Insufficient food intake (score ≥ 3) in 3+ check-ins within 7 days',
    safetyAction: 'show_resources',
    patientMessage: 'You have had trouble eating enough several days in a row. Please talk to your care team.',
    notifyClinician: true,
    windowDays: 7,
    minOccurrences: 3,
  },
  {
    id: 'TREND_SOCIAL_1',
    name: 'Persistent social isolation',
    domain: 'social',
    flagLevel: 2,
    clinicianFlagLabel: 'Significant isolation or loneliness (score ≥ 3) in 4+ check-ins within 14 days',
    safetyAction: 'none',
    patientMessage: 'You have been feeling alone a lot recently. Connection can help — consider reaching out to someone you trust.',
    notifyClinician: false,
    windowDays: 14,
    minOccurrences: 4,
  },
  {
    id: 'TREND_SLEEP_1',
    name: 'Persistent poor sleep',
    domain: 'sleep',
    flagLevel: 2,
    clinicianFlagLabel: 'Poor sleep quality (score ≥ 3) in 4+ check-ins within 7 days',
    safetyAction: 'none',
    patientMessage: 'You have had poor sleep several nights in a row. Sleep affects everything else — let your care team know.',
    notifyClinician: false,
    windowDays: 7,
    minOccurrences: 4,
  },
  {
    id: 'TREND_ACT_1',
    name: 'Persistent very low activity',
    domain: 'activity',
    flagLevel: 2,
    clinicianFlagLabel: 'Very low activity (score ≥ 3) in 5+ check-ins within 14 days',
    safetyAction: 'none',
    patientMessage: 'You have had very low activity for several days. Even small amounts of movement can help.',
    notifyClinician: false,
    windowDays: 14,
    minOccurrences: 5,
  },
  {
    id: 'TREND_ENV_1',
    name: 'Persistent harmful environment',
    domain: 'environment',
    flagLevel: 3,
    clinicianFlagLabel: 'Harmful environment (score ≥ 3) in 4+ check-ins within 14 days',
    safetyAction: 'show_resources',
    patientMessage: 'Your environment has been affecting your health for several days. Your care team may be able to connect you with resources.',
    notifyClinician: true,
    windowDays: 14,
    minOccurrences: 4,
  },
  {
    id: 'TREND_SAFETY_1',
    name: 'Recurring unsafe feelings',
    domain: 'safety',
    flagLevel: 4,
    clinicianFlagLabel: 'Feeling unsafe (score ≥ 3) reported in 2+ check-ins within 14 days — URGENT',
    safetyAction: 'urgent_care',
    patientMessage: 'You have felt unsafe more than once recently. Please tell your care team or a trusted person.',
    notifyClinician: true,
    windowDays: 14,
    minOccurrences: 2,
  },
  {
    id: 'TREND_LIFESTYLE_1',
    name: 'Substance use causing repeated problems',
    domain: 'lifestyle',
    flagLevel: 3,
    clinicianFlagLabel: 'Substance use causing significant problems (score ≥ 3) in 4+ check-ins within 14 days',
    safetyAction: 'show_resources',
    patientMessage: 'Substance use has been affecting you several days in a row. Your care team is here to help — not to judge.',
    notifyClinician: true,
    windowDays: 14,
    minOccurrences: 4,
  },
]
