import type { TriggerRule } from './types'

export const TRIGGER_RULES: TriggerRule[] = [
  // ── PAIN ────────────────────────────────────────────────────────────────────
  {
    id: 'TR_P_1',
    name: 'Severe or very severe pain',
    domain: 'pain',
    condition: { questionId: 'Q_B_M_1', operator: 'in', value: ['severe_pain', 'very_severe_pain'] },
    followUpQuestionIds: ['Q_FU_P_1', 'Q_FU_P_2'],
    flagLevel: 3,
    patientMessage: 'Your pain level is high. Please tell your care team.',
    clinicianFlagLabel: 'Severe pain reported at morning check-in',
    safetyAction: 'show_resources',
    notifyClinician: true,
    includeInSummary: true,
  },
  {
    id: 'TR_P_2',
    name: 'Severe or very severe pain — intermediate/advanced morning',
    domain: 'pain',
    condition: { questionId: 'Q_I_M_2', operator: 'in', value: ['severe_pain', 'very_severe_pain'] },
    followUpQuestionIds: ['Q_FU_P_1', 'Q_FU_P_2', 'Q_FU_P_3'],
    flagLevel: 3,
    patientMessage: 'Your pain level is high. Please tell your care team.',
    clinicianFlagLabel: 'Severe pain reported at morning check-in',
    safetyAction: 'show_resources',
    notifyClinician: true,
    includeInSummary: true,
  },
  {
    id: 'TR_P_3',
    name: 'Chest pain',
    domain: 'pain',
    condition: { questionId: 'Q_FU_P_1', operator: 'contains', value: 'chest' },
    followUpQuestionIds: [],
    flagLevel: 4,
    patientMessage: 'Chest pain can be a sign of a serious problem. Call your doctor or emergency services right away.',
    clinicianFlagLabel: 'Chest pain reported — possible cardiac/urgent event',
    safetyAction: 'urgent_care',
    notifyClinician: true,
    includeInSummary: true,
  },
  {
    id: 'TR_P_4',
    name: 'New or very different pain',
    domain: 'pain',
    condition: { questionId: 'Q_FU_P_2', operator: 'in', value: ['very_different', 'completely_new'] },
    followUpQuestionIds: ['Q_FU_P_3'],
    flagLevel: 3,
    patientMessage: 'New or changed pain is worth discussing with your care team.',
    clinicianFlagLabel: 'New or changed pain pattern reported',
    safetyAction: 'show_resources',
    notifyClinician: true,
    includeInSummary: true,
  },

  // ── MENTAL HEALTH ────────────────────────────────────────────────────────────
  {
    id: 'TR_MH_1',
    name: 'Severe or very severe sadness/hopelessness',
    domain: 'mental_health',
    condition: { questionId: 'Q_I_N_3', operator: 'in', value: ['severe', 'very_severe'] },
    followUpQuestionIds: ['Q_FU_MH_1', 'Q_FU_MH_3'],
    flagLevel: 3,
    patientMessage: 'It sounds like today was very hard emotionally. Support is available.',
    clinicianFlagLabel: 'Severe low mood/hopelessness at night check-in',
    safetyAction: 'show_resources',
    notifyClinician: true,
    includeInSummary: true,
  },
  {
    id: 'TR_MH_2',
    name: 'Thoughts of self-harm — any',
    domain: 'mental_health',
    condition: {
      questionId: 'Q_FU_MH_1',
      operator: 'in',
      value: ['brief_passing_thought', 'thoughts_more_than_once', 'thoughts_with_plan'],
    },
    followUpQuestionIds: ['Q_FU_MH_2'],
    flagLevel: 4,
    patientMessage: 'You are not alone. Please reach out to a crisis line or your care team right now.',
    clinicianFlagLabel: 'Patient endorsed thoughts of self-harm — URGENT',
    safetyAction: 'urgent_care',
    notifyClinician: true,
    includeInSummary: true,
  },
  {
    id: 'TR_MH_3',
    name: 'Thoughts of self-harm with plan',
    domain: 'mental_health',
    condition: { questionId: 'Q_FU_MH_1', operator: 'equals', value: 'thoughts_with_plan' },
    followUpQuestionIds: [],
    flagLevel: 4,
    patientMessage: 'This is a crisis. Please call emergency services or go to the nearest emergency room now.',
    clinicianFlagLabel: 'Patient reported a plan to self-harm — EMERGENCY',
    safetyAction: 'emergency',
    notifyClinician: true,
    includeInSummary: true,
  },
  {
    id: 'TR_MH_4',
    name: 'Cannot find safe support',
    domain: 'mental_health',
    condition: { questionId: 'Q_FU_MH_2', operator: 'equals', value: 'no' },
    followUpQuestionIds: [],
    flagLevel: 4,
    patientMessage: 'You can contact the 988 Suicide & Crisis Lifeline anytime — call or text 988.',
    clinicianFlagLabel: 'Patient has no safe support contact during crisis flag',
    safetyAction: 'urgent_care',
    notifyClinician: true,
    includeInSummary: true,
  },

  // ── SAFETY ───────────────────────────────────────────────────────────────────
  {
    id: 'TR_S_1',
    name: 'Feeling unsafe at home',
    domain: 'safety',
    condition: { questionId: 'Q_FU_S_1', operator: 'contains', value: 'person_at_home' },
    followUpQuestionIds: ['Q_FU_S_2'],
    flagLevel: 4,
    patientMessage: 'Your safety matters. If you are in danger, call 911. Resources are listed below.',
    clinicianFlagLabel: 'Patient reported feeling unsafe at home — possible domestic violence',
    safetyAction: 'urgent_care',
    notifyClinician: true,
    includeInSummary: true,
  },
  {
    id: 'TR_S_2',
    name: 'Currently not in a safe place',
    domain: 'safety',
    condition: { questionId: 'Q_FU_S_2', operator: 'equals', value: 'no' },
    followUpQuestionIds: [],
    flagLevel: 4,
    patientMessage: 'Please move to a safe location. If in immediate danger, call 911.',
    clinicianFlagLabel: 'Patient confirmed they are NOT currently in a safe location — URGENT',
    safetyAction: 'emergency',
    notifyClinician: true,
    includeInSummary: true,
  },

  // ── MEDICATION ───────────────────────────────────────────────────────────────
  {
    id: 'TR_MED_1',
    name: 'Multiple missed doses',
    domain: 'medication',
    condition: {
      questionId: 'Q_I_N_10',
      operator: 'in',
      value: ['missed_more_than_one_dose', 'took_more_than_planned'],
    },
    followUpQuestionIds: ['Q_FU_MED_1', 'Q_FU_MED_2'],
    flagLevel: 3,
    patientMessage: 'Missing multiple doses can affect your health. Please contact your care team.',
    clinicianFlagLabel: 'Multiple missed or altered medication doses',
    safetyAction: 'show_resources',
    notifyClinician: true,
    includeInSummary: true,
  },
  {
    id: 'TR_MED_2',
    name: 'Medication cost or access barrier',
    domain: 'medication',
    condition: { questionId: 'Q_FU_MED_1', operator: 'contains', value: 'cost' },
    followUpQuestionIds: [],
    flagLevel: 3,
    patientMessage: 'If cost is a barrier, your care team may be able to help find options.',
    clinicianFlagLabel: 'Medication cost reported as adherence barrier',
    safetyAction: 'show_resources',
    notifyClinician: true,
    includeInSummary: true,
  },

  // ── DIET ─────────────────────────────────────────────────────────────────────
  {
    id: 'TR_DIET_1',
    name: 'Almost nothing eaten',
    domain: 'diet',
    condition: {
      questionId: 'Q_B_N_5',
      operator: 'equals',
      value: 'almost_nothing',
    },
    followUpQuestionIds: ['Q_FU_D_1'],
    flagLevel: 4,
    patientMessage: 'Eating enough is important for your health and recovery. Can you eat something now?',
    clinicianFlagLabel: 'Patient reported eating almost nothing today',
    safetyAction: 'show_resources',
    notifyClinician: true,
    includeInSummary: true,
  },
  {
    id: 'TR_DIET_2',
    name: 'Food access barrier',
    domain: 'diet',
    condition: { questionId: 'Q_FU_D_1', operator: 'contains', value: 'no_food_available' },
    followUpQuestionIds: [],
    flagLevel: 3,
    patientMessage: 'If you need help getting food, your care team or local services can help.',
    clinicianFlagLabel: 'Food access barrier identified — no food available',
    safetyAction: 'show_resources',
    notifyClinician: true,
    includeInSummary: true,
  },

  // ── ENVIRONMENT ──────────────────────────────────────────────────────────────
  {
    id: 'TR_ENV_1',
    name: 'Unsafe or violent home environment',
    domain: 'environment',
    condition: { questionId: 'Q_FU_E_1', operator: 'contains', value: 'violence_conflict' },
    followUpQuestionIds: ['Q_FU_S_2'],
    flagLevel: 4,
    patientMessage: 'You deserve to be safe. Resources are listed below.',
    clinicianFlagLabel: 'Violence or conflict reported in home environment',
    safetyAction: 'urgent_care',
    notifyClinician: true,
    includeInSummary: true,
  },

  // ── SOCIAL ───────────────────────────────────────────────────────────────────
  {
    id: 'TR_SOC_1',
    name: 'Felt unsafe with someone',
    domain: 'social',
    condition: { questionId: 'Q_FU_SOC_1', operator: 'contains', value: 'felt_unsafe_with_someone' },
    followUpQuestionIds: ['Q_FU_S_1', 'Q_FU_S_2'],
    flagLevel: 4,
    patientMessage: 'No one should make you feel unsafe. Resources and support are listed below.',
    clinicianFlagLabel: 'Patient reported feeling unsafe with a person — possible interpersonal violence',
    safetyAction: 'urgent_care',
    notifyClinician: true,
    includeInSummary: true,
  },
]
